trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group : lza-dev
  - name : Vlocation
    value : ${variabes.location}
  - name : Vtier
    value : ${variabes.tier}
  - name : VtemplateFile
    value : ${variabes.templateFile}
  - name : VnamePrefix
    value : ${variabes.namePrefix}
  - name : VservicePrincipleId
    value : ${variabes.servicePrincipleId}
  - name : VjumpHostPassword
    value : ${variabes.jumpHostPassword}
  - name : VdeploymentName
    value : ${variabes.deploymentName}
  - name : VparamFile
    value : ${variabes.paramFile}
stages:
- stage: Provision_Infrastruture
  jobs:
  - job: show_variables
    steps:
    - task: AzureCLI@2
      displayName: "Output Relevant Variables"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo $(location)
          echo $(tier)
          echo $(namePrefix)
          echo $(servicePrincipleId)
          echo $(deploymentName)
          echo $(Vlocation)
          echo $(Vtier)
          echo $(VnamePrefix)
          echo $(VservicePrincipleId)
          echo $(VdeploymentName)
          echo 'Executing --> az deployment sub create --name $(VdeploymentName) --location $(Vlocation) --template-file $(VtemplateFile) --parameters $(VparamFile) location=$(Vlocation) namePrefix=$(VnamePrefix) principalId=$(VservicePrincipalId) tier=$(Vtier) jumpHostPassword=$(VjumpHostPassword)'
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'
  - job: provision_resources
    steps:
    - task: AzureCLI@2
      displayName: "Provision Various Resources"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az --version'
    - task: AzureCLI@2
      displayName: "Resource Provision Using Bicep"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create --name $(VdeploymentName) --location $(Vlocation) --template-file $(VtemplateFile) --parameters $(VparamFile) location=$(Vlocation) namePrefix=$(VnamePrefix) principalId=$(VservicePrincipalId) tier=$(Vtier) jumpHostPassword=$(VjumpHostPassword)
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'