parameters:
  - name : jobName
    type : string 
  - name : dependsOn
    type : object
  - name : ephemeral
    type : boolean 
  - name : serviceConnection
    type : string 
  - name : resourceGroupName
    type : string
  - name : templateFile 
    type : string
  - name : workingDirectory
    type : string 
jobs:
  - job: ${{parameters.jobName}}
    displayName: "Job: Destroy Infrastructure - ${{parameters.jobName}}"
    dependsOn: ${{parameters.dependson}}
    condition: eq(parameters['ephemeral'], 'true')
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo Deleting Resource Group: ${{parameters.resourceGroupName}}
          echo executing az deployment group create --template-file ${{parameters.templateFile}} --resource-group ${{parameters.resourceGroupName}} --mode complete
          az deployment group create --template-file ${{parameters.templateFile}} --resource-group ${{parameters.resourceGroupName}} --mode complete
          az group delete --name ${{parameters.resourceGroupName}} -y
        workingDirectory: ${{parameters.workingDirectory}}
