parameters:
  - name : jobName
    type : string 
  - name : dependsOn
    type : object
  - name : ignoreError
    type : boolean 
  - name : serviceConnection
    type : string 
  - name : resourceGroupName
    type : string
  - name : appName
    type : string
  - name : springAppServiceName
    type : string
  - name : artifactPath
    type: string
jobs:
  - job: ${{parameters.jobName}}
    displayName: "Job: Deploy App - ${{parameters.jobName}}"
    dependsOn: ${{parameters.dependson}}
    continueOnError: true
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az spring app deploy \
            --resource-group ${{parameters.resourceGroupName}} \
            --service ${{parameters.springAppServiceName}} \
            --name ${{parameters.appName}} \
            --artifact-path ${{parameters.artifactPath}} \
            --env SPRING_PROFILES_ACTIVE=passwordless
        addSpnToEnvironment: true 