parameters:
  - name : jobName
    type : string 
  - name : dependsOn
    type : object
  - name : ignoreError
    type : boolean 
  - name : serviceConnection
    type : string 
  - name : resourceGroupName
    type : string
  - name : appName
    type : string
  - name : springAppServiceName
    type : string
  - name : parameters.targetArtifact
    type: string
  - name : buildType
    type : string
  - name : projectId
    type : string 
  - name : definitinId
    type: string 
  - name : artifactName 
    type: string 
  - name : buildVersionToDownload
    type: string

jobs:
  - job: ${{parameters.jobName}}
    displayName: "Job: Deploy App - ${{parameters.jobName}}"
    dependsOn: ${{parameters.dependson}}
    continueOnError: true
    steps:
    - task: AzureCLI@2
      displayName: Install Azure CLI Spring Extension
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: |
          set -eu
          az extension add --name spring -y
          az spring list -o table
        addSpnToEnvironment: true 
    - task: DownloadPipelineArtifact@2
      displayName: "download build-release artifacts"
      inputs:
        buildType: ${{parameters.buildType}}
        project: ${{parameters.projectId}}
        definition: ${{parameters.definitionId}}
        buildVersionToDownload: ${{parameters.buildVersionToDownload}}
        artifactName: ${{parameters.artifactName}}
        targetPath: '$(Pipeline.Workspace)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo 'Deploying Spring App -- ${{parameters.appName}}'
          az spring app deploy \
            --resource-group ${{parameters.resourceGroupName}} \
            --service ${{parameters.springAppServiceName}} \
            --name ${{parameters.appName}} \
            --artifact-path $(Pipeline.Workspace)/${{parameters.targetArtifact}} \
            --env SPRING_PROFILES_ACTIVE=passwordless
        addSpnToEnvironment: true 