parameters:
  - name: jobName
    type: string
  - name : dependson 
    type: object
  - name: skipProvision
    type: boolean
  - name: serviceConnection
    type: string
  - name: deploymentName
    type: string
  - name: location
    type: string
  - name: namePrefix
    type: string
  - name: templateFile
    type: string
  - name: paramFile
    type: string
  - name: servicePrincipalId
    type: string
  - name: jumpHostPassword
    type: string
  - name: workingDirectory
    type: string
jobs:
  - job: "${{parameters.jobName}}"
    displayName: "Job: Provision Infrastructure - ${{parameters.jobName}}"
    dependsOn: ${{parameters.dependson}}
    condition: eq('${{ parameters.skipProvision }}', false)
    steps:
      - checkout: self
      - task: AzureCLI@2
        #displayName: "Provision Hub Network"
        inputs:
          azureSubscription: ${{parameters.serviceConnection}}
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: |
            az deployment sub create --name ${{parameters.deploymentName}} --location ${{parameters.location}} --template-file ${{parameters.templateFile}} --parameters ${{parameters.paramFile}} location=${{parameters.location}} namePrefix=${{parameters.namePrefix}} principalId=${{parameters.servicePrincipalId}} jumpHostPassword=${{parameters.jumpHostPassword}}
          workingDirectory: ${{parameters.workingDirectory}}
