trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group : lza-dev

stages:
- stage: Deprovision 
  jobs:
  - job: "DeProvisionInfra"
    steps:
    - task: AzureCLI@2
      displayName: "To be Deleted - Testing Purposes"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo $(location)
          echo $(tier)
          echo $(namePrefix)
          echo $(principleId)
          lb=rg-$(namePrefix)-Apps
          echo $lb
          lb2="$(namePrefix)-Apps"
          echo $lb2
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'
- stage: Deprovision APPS
  jobs:
  - job: "DeProvisionAPPS"
    steps:
    - task: AzureCLI@2
      displayName: "Deprovision Resource Group APPS"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          resourceGroup=rg-$(namePrefix)-APPS
          echo Deleting Resource Group: $resourceGroup
          echo executing az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az group delete --name $resourceGroup -y
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'
- stage: Deprovision SHARED
  jobs:
  - job: "DeProvisionSHARED"
    steps:
    - task: AzureCLI@2
      displayName: "Deprovision Resource Group SHARED"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          resourceGroup=rg-$(namePrefix)-SHARED
          echo Deleting Resource Group: $resourceGroup
          echo executing az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az group delete --name $resourceGroup -y
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'
- stage: Deprovision PRIVATEZONES
  jobs:
  - job: "DeProvision_PRIVATEZONES"
    steps:
    - task: AzureCLI@2
      displayName: "Deprovision Resource Group PRIVATEZONES"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          resourceGroup=rg-$(namePrefix)-PRIVATEZONES
          echo Deleting Resource Group: $resourceGroup
          echo executing az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az group delete --name $resourceGroup -y
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'
- stage: Deprovision SPOKE
  jobs:
  - job: "DeProvision_SPOKE"
    steps:
    - task: AzureCLI@2
      displayName: "Deprovision Resource Group SPOKE"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          resourceGroup=rg-$(namePrefix)-SPOKE
          echo Deleting Resource Group: $resourceGroup
          echo executing az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az group delete --name $resourceGroup -y
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'
- stage: Deprovision HUB
  jobs:
  - job: "DeProvision_HUB"
    steps:
    - task: AzureCLI@2
      displayName: "Deprovision Resource Group HUB"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          resourceGroup=rg-$(namePrefix)-HUB
          echo Deleting Resource Group: $resourceGroup
          echo executing az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az group delete --name $resourceGroup -y
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'
- stage: Deprovision NetworkWatcherRG
  jobs:
  - job: "DeProvision_NetworkWatcherRG"
    steps:
    - task: AzureCLI@2
      displayName: "Deprovision Resource Group: NetworkWatcherRG"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          resourceGroup=NetworkWatcherRG
          echo Deleting Resource Group: $resourceGroup
          echo executing az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az deployment group create --template-file $(deleteTemplateFile) --resource-group $resourceGroup --mode complete
          az group delete --name $resourceGroup -y
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'