trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  -group : lza-dev

  
stages:
- stage: Provision 
  jobs:
  - job: "DeProvisionInfra"
    steps:
    - task: AzureCLI@2
      displayName: "Deprovision Infrastructure"
      inputs:
        azureSubscription: 'scSub002'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo '$(location)'
          echo '$(tier)'
          echo '$(namePrefix)'
          echo '$(servicePrincipleId)'
          #location = "eastus"
          #namePrefix = "qaEnv"
          #principalId='35f307a2-474a-45bb-a4df-b84423552cf2'
          #az deployment group create --template-file empty.bicep --resource-group rg-devEnv-APPS --mode complete
          #az deployment sub create --name "test-Standard" --location $(location) --template-file $(templateFile) --parameters $(paramFile) location=$(location) namePrefix=$(namePrefix) principalId=$(servicePrincipalId) tier=$(tier) jumpHostPassword="P0ssWord"
        workingDirectory: 'Scenarios/ASA-Secure-Baseline/Bicep/Deployment'

 